---

- name: Include distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'

- debug: var=monclient_remove
- debug: var=ansible_system
- debug: var=nrpeclient_packages
- block:
    - name: nrpe & plugins packages install
      package: name={{nrpeclient_packages}} state=present
## on lxc containers: "error: unpacking of archive failed on file /usr/sbin/fping: cpio: cap_set_file"
      ignore_errors: true
## FIXME! fatal: [test-ob]: FAILED! => {"changed": false, "failed": true, "msg": "failed in get_package_state(): Error from http://ftp.OpenBSD.org/pub/OpenBSD/6.0/packages/i386/p5-Monitoring-Plugin-0.39p0,.tgz\nftp: Error retrieving file: 404 Not Found\nError from http://ftp.OpenBSD.org/pub/OpenBSD/6.0/packages/i386/p5-Monitoring-Plugin-0.39p0,.tgz\nftp: Error retrieving file: 404 Not Found\nError from http://ftp.OpenBSD.org/pub/OpenBSD/6.0/packages/i386/p5-HTML-StripScripts].tgz\nftp: Error retrieving file: 404 Not Found\n"}
      #when: ansible_system == 'Linux' or ansible_system == 'OpenBSD'
      when: ansible_system == 'Linux'
    - block:
        - name: nrpe & plugins packages install - openbsd
          openbsd_pkg: name={{ nrpeclient_packages }} state=present
      when: ansible_system == 'OpenBSD'
    - include: darwin.yml
      when: ansible_os_family == 'Darwin'

    - include: nrpe.yml
    - include: nrpe-server-register.yml
    - include: ntp.yml
      when: >
        nrpeclient_watch_ntp and
        not (ansible_virtualization_type is defined and
              (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker")
            ) and
        not ansible_os_family == "RedHat"

    - include: chrony.yml
      when: nrpeclient_watch_ntp and ansible_os_family == "RedHat"

    - name: Ensure services are enabled and started
      service: name={{ nrpe_svc }} state=started enabled=yes
      when: ansible_system == 'Linux'
  when: (monclient_remove is not defined or not monclient_remove)

- include: remove.yml
  when: monclient_remove is defined and monclient_remove
