---

- name: nrpeclient_server
  debug: var=nrpeclient_server
#- fail: msg="Server is not configured. Missing commands-custom.conf... Stopping!"
- debug: msg="Server is not configured. Missing commands-custom.conf... Skipping server configuration!"
  when: not nrpecmd.stat.exists and nrpeclient_server is defined and nrpeclient_server != 'test-kitchen' and nrpeclient_server != 'ansible_fqdn_servername'
- block:
    - stat: path=/etc/icinga2/conf.d/commands-custom.conf
      register: nrpecmd
      delegate_to: "{{ nrpeclient_server }}"
      changed_when: False

    - name: ensure right permissions for /etc/icinga2/conf.d
      file: dest=/etc/icinga2/conf.d state=directory mode=0755
      delegate_to: "{{ nrpeclient_server }}"
    - debug: var=nrpeclient_hostname
    - debug: var=nrpeclient_server
    - name: deploy client configuration on icinga2 server
      template: src=hosts-template.conf.j2 dest="/etc/icinga2/conf.d/hosts-monclient-{{ inventory_hostname }}.conf" mode=0644
      delegate_to: "{{ nrpeclient_server }}"
      notify:
        - restart icinga2 server
    #  when: nrpe_mode is defined and nrpe_mode
    ## FIXME! nrpeclient_server conditions does not seem to work
      when: nrpeclient_type is defined and nrpeclient_type == 'icinga2'

    - name: deploy client configuration on nagios server
      template: src=hosts-template-nagios.cfg.j2 dest=/etc/nagios3/conf.d/hosts-monclient-{{ ansible_fqdn }}.cfg mode=0644
      delegate_to: "{{ nrpeclient_server }}"
      notify:
        - restart nagios server
      when: nrpeclient_type is defined and nrpeclient_type == 'nagios'

    - name: add client to server /etc/hosts
      lineinfile: dest=/etc/hosts line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_hostname }}.home"
      delegate_to: "{{ nrpeclient_server }}"
      when: nrpeclient_add_to_etchosts is defined and nrpeclient_add_to_etchosts

  when: (nrpeclient_server is defined and nrpeclient_server != 'test-kitchen' and nrpeclient_server != 'ansible_fqdn_servername')
#  when: not (not nrpecmd.stat.exists and nrpeclient_server is defined and nrpeclient_server != 'test-kitchen' and nrpeclient_server != 'ansible_fqdn_servername')

